<?php
/**
 * Created by PhpStorm.
 * User: Kondziu
 * Date: 2016-02-06
 * Time: 22:08
 */
namespace models;
require_once 'model.php';
require_once 'transportMedium.php';

class delegationRoad extends model
{
	public $id;
	public $placeFrom;
	public $placeTo;
	public $distance;
	public $dateStart;
	public $dateFinish;
	public $transportMedium;
	public $cost;
	private $deleted;

	/**
	 * delegationRoad constructor.
	 * @param $id
	 * @param $placeFrom
	 * @param $placeTo
	 * @param $distance
	 * @param $dateStart
	 * @param $dateFinish
	 * @param $transportMedium
	 */
	public function __construct()
	{

	}

	public function isDeleted()
	{
		if($this->deleted == 1) return true;
		return false;
	}

	public function getTransportMediumName()
	{
		return $this->transportMedium->name;
	}

	public function save()
	{
		parent::save(); // TODO: Change the autogenerated stub
	}

	public static function getByDelegationId($id)
	{
		global $sql;
		$result = array();
		$result = $sql->query("SELECT * FROM delegationroad WHERE delegationId='$id'");
		foreach($result as $r)
		{
			$d  = new delegationRoad();
			$d->id = $r['roadId'];
			$d->placeFrom = $r['placeFrom'];
			$d->placeTo = $r['placeTo'];
			$d->dateStart = str_replace(' ','T',substr($result[0]['dateStart'],0,16));
			$d->dateFinish = str_replace(' ','T',substr($result[0]['dateFinish'],0,16));
			$d->distance = $r['distance'];
			$d->transportMedium = transportMedium::getTransportMedium($r['transportMedium']);
			$d->cost = $r['cost'];
			$d->deleted = $r['deleted'];
			$resultArr[] = $d;
		}
		return $resultArr;
	}

	public function getById($id)
	{
		parent::getById($id); // TODO: Change the autogenerated stub
	}


}